default:
  #默认的下载客户端qbittorrent/transmission
  download_client: 'qbittorrent'
  rule_dir: '/data/rules'
  media_server: 'emby'
  #default media_server的值为emby时会选择这个配置
emby:
  api_key: '去emby申请apikey复制到这里'
  host: '192.168.1.111'
  https: false
  port: 8096
#default media_server的值为plex时会选择这个配置
plex:
  url: 'http://你的plex服务地址:32400'
  token: 'https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/ 从这里学习如何获取token'
qbittorrent:
  #如果你的qbit需要登陆，这个地方需要改成true
  need_login: false
  #这里要填写qbit的访问地址
  url: 'http://192.168.1.11:8080/'
  #need_login为true时需要配置账号密码
  username: admin
  password: admin
transmission:
  #这里填写transmission的地址即可
  host: '192.168.1.10'
  port: 49166
  username: 'user'
  password: 'pass'
pt:
  #目前支持的站点配置示范都已经列出了，如果你只有一个，就把相关配置项直接删除
  mteam:
    #登陆方式cookie/user，建议都使用cookie，不建议使用账号密码的方式；如果type为user，需要提供username、password配置项
    type: 'cookie'
    cookie: ''
  hdsky:
    type: 'cookie'
    cookie: ''
  tjupt:
    type: 'cookie'
    cookie: ''
  hdchina:
    type: 'cookie'
    cookie: ''
  ssd:
    type: 'cookie'
    cookie: ''
  chdbits:
    type: 'cookie'
    cookie: ''
  keepfrds:
    type: 'cookie'
    cookie: ''
  jackett:
    address: 'http://192.168.1.10:9117'
    api_key: '111'
sources:
  #目前仅支持douban_wish，这里不需要改动
  - type: 'douban_wish'
    args:
      #true/false 是否自动翻页
      turn_page: true
      #wish 想看 do 在看 collect看过
      types: 'wish;do'
      #监听的豆瓣用户名id，手机app中点头像-资料与账号，可以看到豆瓣id；可以访问https://movie.douban.com/people/user1/wish 页面看是否正确
      user_domain: 'user1;'
      #最近N天加入到你豆瓣想看列表的电影
      within_days: 365
      #注意，只有极少数情况下，豆瓣的电影需要登陆后才可以访问获取，比如https://movie.douban.com/subject/23748525/ 电脑不登陆访问不了；可以留空，等遇到报错再配置；
      ##2022.02.06调整 之前豆瓣cookie的位置放错了
      cookie: ''
tasks:
  #任务配置，每一个- 开头的就是一个任务定义
  - type: 'sync_movies'
    #2022.02.06新增 任务调度周期支持自定义
    cron: '0 0-2,9-23 * * *'
    args:
      source: 'douban_wish'
      #设置搜索的pt站，支持多pt同时搜索。多个用英文;隔开
      search_pt: 'mteam;hdsky'
      #选择最佳种子的规则配置，compact 紧凑型硬盘规则，选择方面会注重高压缩比的小尺寸资源；compress 全压缩格式，但这个会选到原盘无损压缩；collection 收藏级规则，会重点选择remux和蓝光原盘；默认使用全压缩文件选种策略，避开原盘资源
      score_rule: 'compress'
      #某资源首个种子过去多久，才进行检索下载；有些资源刚出来质量并不好，等几个小时，发种人变多，才有的选；
      debut_passed_hours: 6
      #是否自动删除下载的种子，如果不删除，将保留在你映射的/data目录内
      delete_torrent: false
      save_mode:
        - type: 电影
          #path和my_cate 二选一即可
          path: '/downloads/电影'
          #下载完成后自动识别电影信息并采用硬链接或复制的方式，将种子下载后的文件复制到此目录；使用此功能需要完成movies_config.yml配置
          #如果设置了这个值，务必要给容器挂载这个目录。同时不管是用my_cate还是path决定保存路径，都要把下载工具下载后保存的路径挂载给容器
          link_path: '/link/电影'
        - type: 剧集
          my_cate: 电视节目
  #监控下载工具种子状态的任务。种子完成后，可以发送通知、做影视剧整理；
  - type: 'monitor_torrent'
    cron: '*/1 * * * *'
    args:
      complete_notify:
        - 'bark'
      #开启全量种子监测，适用于不想通过机器人下载电影，而是手动提交下载，但还想要使用机器人的智能整理及通知功能的用户，默认false为不开启；
      #开启这个选项为true时，必须配置好movies_config.yml中manager download_paths，否则机器人识别不到资源是什么，会整理和通知出错
      monitor_all_torrents: false